### ISSUE TITLE
Form not submitting

### ISSUE THREAD

**Issue by Paulsky** [konsulting/nova-target#2]
Hello,

Thank you for this package! Disappointing that it's nessecary. But anyway;

I have installed the package via Composer and I'm using it in a specific resource. Like this:
```
\Konsulting\NovaTarget\NovaTarget::make('')
    ->hideCreateAndAddAnotherButton()
```

But unfortuatly, the form is not submitting when the field is included. I get a error message 'There was a problem submitting the form'. When I remove the field, the form submits without a problem (even if I submit the form via the 'Create button'.

**Comment by Keoghan** [comment]
Hi - please can you check the version that was installed?

**Comment by Paulsky** [comment]
Thank you for your quick reply. I'm on version 1.0.0 and Laravel Nova 4.22.2

**Comment by Keoghan** [comment]
Great, thanks, could you try 1.0.1 please?

**Comment by Paulsky** [comment]
Ah I see. 1.0.1 was not installing because of the requirement of `"laravel/nova": "^4.26"`. I will try to fix it.

**Comment by Paulsky** [comment]
Awesome, that fixed it. Thank you once again!🙏
